name: Test

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: "-*"
          version: "14"
          lines-changed-only: true
          thread-comments: true
      - run: make
      - uses: actions/cache@v3
        with:
          path: testbuf
          key: testbuf-${{ github.run_id }}

  testbuf:
    runs-on: ubuntu-22.04
    needs: compile
    steps:
      - uses: actions/cache@v3
        with:
          path: testbuf
          key: testbuf-${{ github.run_id }}
      - run: ./testbuf | grep "Passed all tests."
